bundler_args: --without development
language: ruby
matrix:
  allow_failures:
    - rvm: ruby-head
rvm:
  - rbx-19mode
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ruby-head
gemfile:
  - Gemfile
  - gemfiles/twitter4_0.gemfile
  - gemfiles/twitter4_1.gemfile
  - gemfiles/twitter4_2.gemfile
  - gemfiles/twitter4_3.gemfile
